### ISSUE TITLE
Left-align daily details

### ISSUE THREAD

**Issue by mhkeller** [vsergeev/briefsky#14]
It would be easier to scan if they were all justified.

Current:
![IMG_2994](https://user-images.githubusercontent.com/498744/232973282-bba75a22-c065-485b-bfb2-4ad873ec9a95.jpg)

Left-aligned:
![IMG_2995](https://user-images.githubusercontent.com/498744/232973277-48a20351-8f1e-431c-bfc8-ea7d541ca7cc.PNG)

**Comment by vsergeev** [comment]
I agree the latter reads better. I think the only issue I had ran into was centering the entire block across the page, but you may have already fixed that in this version.
