### ISSUE TITLE
Feature request: show arrow for wind direction

### ISSUE THREAD

**Issue by Noexpert** [vsergeev/briefsky#17]
If possible, could you also show an arrow for the wind direction?
Or at least add it to the options?

I find `⬉` more intuitive than `NW`.
Thanks

**Comment by vsergeev** [comment]
Sure, can add. Do you think it should show both or just one?

**Comment by Noexpert** [comment]
Thanks. Personally, I would only show the arrow, as it's quite easy to understand.
But I don't want to annoy those that like to see the letters, so you could show both.

Thank you
