### ISSUE TITLE
Plot precipitation amount (mm) as bars to distinguish from probability (%).

### ISSUE THREAD

**Issue by Leftium** [vsergeev/briefsky#24]
**Since both precipitation amount (mm) and probability (%) are plotted as lines:**
- It makes it difficult to (quickly) tell which line is which
- The probability is an instantaneous measurement, while the amount is accumulated over the entire hour. 
- When the lines cross it seems there might be a special meaning (but there isn't)

![image](https://github.com/vsergeev/briefsky/assets/381217/183bd40e-25d8-43cc-bf2f-11278f66210d)

**If the plot types for precipitation amount (mm) and probability (%) are different:**
- The chart becomes easier to read and less confusing.
- Precipitation amount is not a continuous measurement, so a bar chart naturally represents how much rain will fall within that hour, where the width of the bar denotes the hour on the x-axis.

![image](https://github.com/vsergeev/briefsky/assets/381217/1e49f5b7-d89d-422d-903b-c3445a064299)

**It is possible to combine other the other metrics into the chart, too:**
![image](https://github.com/vsergeev/briefsky/assets/381217/2187387e-2d6a-4b54-8476-a86770b54f34)

**References**

- [The case against dual axis charts](https://hw.leftium.com/#/item/40391614)
- https://weather-sense.leftium.com/

**Comment by vsergeev** [comment]
Agree this makes more sense. I'll look into switching these into bars for the next release.
