### ISSUE TITLE
PWA Icon

### ISSUE THREAD

**Issue by mhkeller** [vsergeev/briefsky#7]
Would it be possible to create more of a simple icon so that when you add this to your home screen, it has more of a native app look? 

Here's what it looks like currently:
![IMG_2788](https://user-images.githubusercontent.com/498744/228294731-73c95e9f-948f-4cbe-890b-7ae430b0700b.jpg)

**Comment by vsergeev** [comment]
Currently, there's just a simple a favicon. Do you know if the home screen is looking for the icon by some other standardized path?

**Comment by vsergeev** [comment]
Ah, I'm guessing it may be looking at the icons field in this manifest: https://developer.mozilla.org/en-US/docs/Web/Manifest

**Comment by mhkeller** [comment]
Yep I believe that's right about the manifest
