### ISSUE TITLE
PWA Support

### ISSUE THREAD

**Issue by Shadowspear123** [vsergeev/briefsky#8]
Thanks for making this lovely website! It would be great if it could be supported as a PWA on ios. That would give it a native app feel and experience. A weather website which does this nicely is Merry Sky (https://merrysky.net/)

**Comment by vsergeev** [comment]
Yeah, this would be nice to have. I think it'll start with resolving #7 and making it installable as a PWA. After that, I'll see what additional features it needs to behave properly as a PWA.
